### PR TITLE
Support specified domain and dictionary to discover

### PR DESCRIPTION
**Pull request by M09Ic**
example: 
`dnsx -w word.txt -d shein.com -resp -a`
or
`cat word.txt | dnsx -d shein.com -resp -a`

word.txt:
```
www
oa
m
```

result:
```
                projectdiscovery.io
Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
m.shein.com [23.50.233.158]
m.shein.com [23.50.233.166]
m.shein.com [23.50.233.157]
m.shein.com [23.50.233.160]
m.shein.com [23.50.233.152]
m.shein.com [23.50.233.165]
m.shein.com [23.50.233.176]
m.shein.com [23.50.233.150]
m.shein.com [23.50.233.167]
www.shein.com [23.50.233.231]
www.shein.com [23.50.233.222]
www.shein.com [23.50.233.206]
www.shein.com [23.50.233.208]
www.shein.com [23.50.233.207]
www.shein.com [23.50.233.216]
www.shein.com [23.50.233.143]
www.shein.com [23.50.233.224]
www.shein.com [23.50.233.213]
```

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
Useful addition @M09Ic, thank you for adding this, we can also add validation for `w` and `l` flags to be not used at the same time to avoid possible confusion.

**Review by Mzack9999 — APPROVED** [review]

**Comment by M09Ic** [comment]
add domain list file support.

example:
`dnsx -dL domains.txt -w words.txt -resp -a`

domains.txt:
```
shein.com
baidu.com
```

words.txt:
```
www
oa
m
```

result:
```
Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
m.baidu.com [103.235.46.211]
m.baidu.com [103.235.46.212]
m.shein.com [104.109.129.169]
m.shein.com [104.109.129.195]
www.shein.com [23.50.233.200]
www.shein.com [23.50.233.215]
www.shein.com [23.50.233.208]
www.shein.com [23.50.233.183]
www.baidu.com [104.193.88.77]
www.shein.com [23.50.233.189]
www.baidu.com [104.193.88.123]
www.shein.com [23.50.233.191]
www.shein.com [23.50.233.214]
www.shein.com [23.50.233.222]
www.shein.com [23.50.233.205]
```

**Comment by M09Ic** [comment]
> Useful addition @M09Ic, thank you for adding this, we can also add validation for `w` and `l` flags to be not used at the same time to avoid possible confusion.

I added validation for `w && l` confusion issue and null wordlist input with -d  flags issue.

Is there anything else I haven't thought through?

**Comment by M09Ic** [comment]
To keep the command line style uniform. Can we only use the -l or stdin input and set the -enum(bool) flag to enable enumeration mode?

Example:
`echo shein.com | dnsx -w words.txt -enmu`
or
`dnsx -l domains.txt -w words.txt -enmu`

Is this clearer than -d/-dL and -w/stdin?

**Review by ehsandeep — COMMENTED** [review]
@M09Ic we can take `-r, -resolver` flag as an example to accept single or multiple comma separate values and file input support with the same flag to avoid introducing new flag `dL` for taking domain list input from file.

**Comment by ehsandeep** [comment]
> To keep the command line style uniform. Can we only use the -l or stdin input and set the -enum(bool) flag to enable enumeration mode?
> 
> Example: `echo shein.com | dnsx -w words.txt -enum` or `dnsx -l domains.txt -w words.txt -enum`
> 
> Is this clearer than -d/-dL and -w/stdin?

we can avoid changing the existing default behavior that accepts the list (`l`) of subdomains for DNS resolution as stdin.

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
Marking the PR with `changes requested` - as implementation discussion is still in progress

**Comment by M09Ic** [comment]
> > To keep the command line style uniform. Can we only use the -l or stdin input and set the -enum(bool) flag to enable enumeration mode?
> > Example: `echo shein.com | dnsx -w words.txt -enum` or `dnsx -l domains.txt -w words.txt -enum`
> > Is this clearer than -d/-dL and -w/stdin?
> 
> we can avoid changing the existing default behavior that accepts the list (`l`) of subdomains for DNS resolution as stdin.

I'm sorry about my poor English, I can't express myself clearly, so please read my code.

code: https://github.com/M09Ic/dnsx/commit/e01aea560e9a20af38b499c0f3edbda6c8b302be

I want to use -emun flag instead of -d/-dL.   Because the stdin used in -l and -w may cause confusion. So, we only use stdin in -l. and the meaning of -l does not change, it is still hosts/domains

example:

origin:
`echo www | dnsx -d shein.com`

changed
`echo shein.com | dnsx -w words.txt -emun`

I want to remove the -d/-dL flag, and keep the -l/stdin meaning unchanged.

**Comment by ehsandeep** [comment]
@M09Ic thanks for the additional context and yes, we can keep the original behavior of `list/l/stdin` unchanged, and instead of introducing `enum` flag, so we can keep the `d/domain` flag to work along with `w/word` flag for brute force. 

`d/domain` can accept single or multiple or file input similar to the `r/resolver` flag to avoid multiple flags for file list input.

```yaml
INPUT:
   -l, -list string     List of sub(domains)/hosts for DNS resolution (stdin)
   -d, -domain string   List of domain to bruteforce with wordlist (file or comma separated) 
   -w, -word string     List of subdomains to bruteforce  (file or comma separated)
```

```
cat list.txt | dnsx
dnsx -w words.txt -d google.com
dnsx -w app,www -d google.com
dnsx -w app,www -d domains.txt
```

and validation for the `l` flag to be not used with `d` and `w` flag.

**Comment by M09Ic** [comment]
1. Add -d flag to support comma separated input with any use.
2. Supports more flexible configurations

` ./dnsx.exe  -d aliyun.com -w word.txt  -enum -silent | ./dnsx.exe -w word.txt -enum -silent`
or
`echo "aliyun.com" | ./dnsx.exe -w word.txt -enum -silent  | ./dnsx.exe -w word.txt -enum -silent`

multiple domains:
`./dnsx.exe -l domains.txt -w word.txt -enum -slient | ./dnsx.exe -w word.txt -enum -silent`
or
`cat domains.txt | ./dnsx.exe -w word.txt -enum -slient | ./dnsx.exe -w word.txt -enum -silent`

(I still think that adding the -enum flag will change the code as little as possible, and will not affect the original meaning of other flags.  If you have better comments, you can directly modify my code. Because I don't know if I can change the original code as little as possible.)

**Review by ehsandeep — APPROVED** [review]
Thank you @M09Ic for adding this support, few minor changes we will make related to this feature before pushing the changes to master, will keep you posted once we make those changes.

- optional stdin support for `d` and `w` flag
- file input support for `d` flag
- validation for `l`, `d`, `w` flag
- possible bug fixes (not necessarily related to this PR)

**Pull request merged**
