### PR TITLE
Adding ANY Query functionality

### PR DESCRIPTION
**Pull request by Ahmadkashif**
Supportive part of the implementation present in the 'retryabledns' repo

### CODE REVIEW

**Comment by Ahmadkashif** [comment]
Is there a specific log message/s on your side that can help me understand the problem better @ehsandeep ?

**Comment by ShubhamRasal** [comment]
```console
❯ echo hollisterco.com | ./dnsx -any -silent
hollisterco.com

❯ echo hollisterco.com | ./dnsx -any -resp -silent
hollisterco.com [96.17.150.106] 
hollisterco.com [96.17.150.152] 
hollisterco.com [a1-58.akam.net] 
hollisterco.com [a26-65.akam.net] 
hollisterco.com [a9-65.akam.net] 
hollisterco.com [a3-66.akam.net] 
hollisterco.com [a8-64.akam.net] 
hollisterco.com [a4-67.akam.net] 
hollisterco.com [facebook-domain-verification=2mzk0qbipizvvhkmbopcqpdwtaq70o] 
hollisterco.com [spycloud-domain-verification=cdc1c551-cd9f-4728-893d-e93f414b83e7] 
hollisterco.com [533a7d7f619a456caff4aa2b0433a811.hollisterco.com] 
hollisterco.com [v=spf1 include:spf-0026d501.pphosted.com include:spf.mandrillapp.com ~all] 
hollisterco.com [ms=ms88661693] 
hollisterco.com [mxb-0026d501.gslb.pphosted.com] 
hollisterco.com [mxa-0026d501.gslb.pphosted.com] 
hollisterco.com [blox-anf-dns-pr20-v.homeoffice.anfcorp.com.] 
hollisterco.com [please_set_email.absolutely.nowhere.] 
```

**Comment by ShubhamRasal** [comment]
<details>
  <summary>JSON OUTPUT</summary>

```json
{
  "host": "hollisterco.com",
  "ttl": 21600,
  "resolver": [
    "1.0.0.1:53",
    "8.8.8.8:53"
  ],
  "a": [
    "96.17.150.106",
    "96.17.150.152"
  ],
  "mx": [
    "mxa-0026d501.gslb.pphosted.com",
    "mxb-0026d501.gslb.pphosted.com"
  ],
  "any": [
    "96.17.150.106",
    "96.17.150.152",
    "a3-66.akam.net",
    "a4-67.akam.net",
    "a26-65.akam.net",
    "a1-58.akam.net",
    "a9-65.akam.net",
    "a8-64.akam.net",
    "spycloud-domain-verification=cdc1c551-cd9f-4728-893d-e93f414b83e7",
    "facebook-domain-verification=2mzk0qbipizvvhkmbopcqpdwtaq70o",
    "v=spf1 include:spf-0026d501.pphosted.com include:spf.mandrillapp.com ~all",
    "MS=ms88661693",
    "533a7d7f619a456caff4aa2b0433a811.hollisterco.com",
    "mxa-0026d501.gslb.pphosted.com",
    "mxb-0026d501.gslb.pphosted.com",
    "blox-anf-dns-pr20-v.homeoffice.anfcorp.com.",
    "please_set_email.absolutely.nowhere."
  ],
  "soa": [
    {
      "ns": "blox-anf-dns-pr20-v.homeoffice.anfcorp.com.",
      "mailbox": "please_set_email.absolutely.nowhere.",
      "serial": 2005012228,
      "refresh": 10800,
      "retry": 3600,
      "expire": 2592000,
      "minttl": 900
    }
  ],
  "ns": [
    "a3-66.akam.net",
    "a4-67.akam.net",
    "a26-65.akam.net",
    "a1-58.akam.net",
    "a9-65.akam.net",
    "a8-64.akam.net"
  ],
  "txt": [
    "spycloud-domain-verification=cdc1c551-cd9f-4728-893d-e93f414b83e7",
    "facebook-domain-verification=2mzk0qbipizvvhkmbopcqpdwtaq70o",
    "v=spf1 include:spf-0026d501.pphosted.com include:spf.mandrillapp.com ~all",
    "MS=ms88661693",
    "533a7d7f619a456caff4aa2b0433a811.hollisterco.com"
  ],
  "all": [
    "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 1232",
    "hollisterco.com.\t21600\tIN\tSOA\tblox-anf-dns-pr20-v.homeoffice.anfcorp.com. please_set_email.absolutely.nowhere. 2005012228 10800 3600 2592000 900",
    "hollisterco.com.\t21600\tIN\tTXT\t\"spycloud-domain-verification=cdc1c551-cd9f-4728-893d-e93f414b83e7\"",
    "hollisterco.com.\t21600\tIN\tTXT\t\"facebook-domain-verification=2mzk0qbipizvvhkmbopcqpdwtaq70o\"",
    "hollisterco.com.\t21600\tIN\tTXT\t\"v=spf1 include:spf-0026d501.pphosted.com include:spf.mandrillapp.com ~all\"",
    "hollisterco.com.\t21600\tIN\tTXT\t\"MS=ms88661693\"",
    "hollisterco.com.\t21600\tIN\tTXT\t\"533a7d7f619a456caff4aa2b0433a811.hollisterco.com\"",
    "hollisterco.com.\t21600\tIN\tNS\ta3-66.akam.net.",
    "hollisterco.com.\t21600\tIN\tNS\ta4-67.akam.net.",
    "hollisterco.com.\t21600\tIN\tNS\ta26-65.akam.net.",
    "hollisterco.com.\t21600\tIN\tNS\ta1-58.akam.net.",
    "hollisterco.com.\t21600\tIN\tNS\ta9-65.akam.net.",
    "hollisterco.com.\t21600\tIN\tNS\ta8-64.akam.net.",
    "hollisterco.com.\t300\tIN\tMX\t100 mxa-0026d501.gslb.pphosted.com.",
    "hollisterco.com.\t300\tIN\tMX\t100 mxb-0026d501.gslb.pphosted.com.",
    "hollisterco.com.\t20\tIN\tA\t96.17.150.106",
    "hollisterco.com.\t20\tIN\tA\t96.17.150.152",
    "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 512"
  ],
  "status_code": "NOERROR",
  "timestamp": "2023-06-08T10:24:39.981928427+05:30"
}
```
</details>

cc @ehsandeep

**Comment by ShubhamRasal** [comment]
```console
❯ echo hollisterco.com | ./dnsx -any -a -json | jq .

      _             __  __
   __| | _ __   ___ \ \/ /
  / _' || '_ \ / __| \  / 
 | (_| || | | |\__ \ /  \ 
  \__,_||_| |_||___//_/\_\

		projectdiscovery.io

[INF] Current dnsx version 1.1.4 (latest)

```

**Review by ehsandeep — CHANGES_REQUESTED** [review]
This works

```console
echo hollisterco.com | ./dnsx -any -silent
hollisterco.com
```

Not this

```console
echo hollisterco.com | ./dnsx -any -a -silent
```

Expected:

```console
echo hollisterco.com | ./dnsx -any -a -silent
hollisterco.com
hollisterco.com
```

cc @ShubhamRasal

**Comment by Mzack9999** [comment]
Depends on https://github.com/projectdiscovery/retryabledns/pulls

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
